spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/FoodAholicTuffy/cloud-config.git
          search-paths: respo
          username: FoodAholicTuffy
          password: xudanmyfirstlove
#  zipkin:
#    base-url: http://localhost:9411
server:
  port: 8888
eureka:
  client:
    service-url:
      deafaultZone: http://localhost:8761
#端口须为8888，若修改默认端口号，则在bootstrap.yml文件中修改