spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/FoodAholicTuffy/cloud-config.git
          search-paths: respo
          username: FoodAholicTuffy
          password: asasdasdasdds
  zipkin:
    base-url: http://192.168.43.20:9411
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://192.168.43.20:8761
#端口须为8888，若修改默认端口号，则在bootstrap.yml文件中修改